import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";

const NotoSansJP = Noto_Sans_JP({
	variable: "--font-noto-sans-jp",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={cn(
					NotoSansJP.variable,
					"h-svh bg-[linear-gradient(to_bottom,_#2567e8_50%,_#f6f8fa_50%)] antialiased text-sm text-medium",
				)}
			>
				{children}
			</body>
		</html>
	);
}
